### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by LoneWolfHT** [DELTA-FORCE-CTF/colorscreens#1]
@DELTA-FORCE-CTF 
You don't need to put each release in this repo. You should use [tags](https://github.com/DELTA-FORCE-CTF/colorscreens/releases) instead (Click 'make new release' and it will save the repo's current state)
BTW GitHub puts everything in a folder when it's downloaded. So users have to copy & paste your mod out of their download. Which can be annoying for `git clone` users.
I recommend you learn how to use git too (`sudo apt install git` for me). There are a lot of tutorials out there that can help you learn how it works. It helps a lot with maintaining and contributing to mods.

Some of the main git commands I use are:
**git clone <url>** - Downloads git repo (url example: https://github.com/DELTA-FORCE-CTF/colorscreens.git) 
**git commit -a -m "<Commit message>"** - Commits all changes made to your local repo with the specified message
**git push** - Pushes your changes to the Github repo
**git status** - Lists changes to your local repo and a few other things

To make changes to your mod with git you would do something similar to this:
**cd minetest/mods/**
**git clone https://github.com/DELTA-FORCE-CTF/colorscreens.git**
**cd ./colorscreens/**
*Make your changes to /minetest/mods/colorscreens/*
**git status**
**git commit -a -m "This is a commit message"**
**git status**
**git push**

**Comment by DELTA-FORCE-CTF** [comment]
Fixed
